services:
  - type: web
    name: markov-music-generator
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT webapp:app
    healthCheckPath: /healthz
